// ========================================
// PLANETARY STUDENT TIMELINE DATA
// Complete Dataset for Network Visualization
// ========================================

const ERAS = {
    'foundational': { name: 'Foundational Period', start: 1857, end: 1899 },
    'formal-curriculum': { name: 'Formal Curriculum Development', start: 1900, end: 1919 },
    'consolidation': { name: 'Pedagogical Consolidation', start: 1920, end: 1949 },
    'philosophy-revolution': { name: 'Educational Philosophy Revolution', start: 1950, end: 1969 },
    'environmental-social': { name: 'Environmental and Social Consciousness', start: 1970, end: 1989 },
    'digital-revolution': { name: 'Digital Revolution in Pedagogy', start: 1990, end: 2009 },
    'contemporary': { name: 'Contemporary Pedagogical Innovation', start: 2010, end: 2019 },
    'emerging': { name: 'Emerging Pedagogical Frontiers', start: 2020, end: 2025 }
};

const FOCUS_AREAS = {
    'FA01': 'Curriculum',
    'FA02': 'Program Structure',
    'FA03': 'Studio Methods',
    'FA04': 'Technology',
    'FA05': 'Social Justice',
    'FA06': 'Collaboration'
};

const PEDAGOGICAL_PRIORITIES = {
    'PP01': 'The Discipline',
    'PP02': 'The Design Studio',
    'PP03': 'The Academic Program'
};

const ENTRY_TYPES = {
    'PD': 'Pedagogical Development',
    'ID': 'Institutional Development',
    'BIB': 'Theoretical Foundation'
};

// Complete Timeline Entries - 166 entries
const timelineEntries = [
    {id:1,year:1857,location:'New York, NY, USA',title:'Collaborative Design Philosophy',description:'Olmsted and Vaux establish collaborative design methodology through Central Park competition, creating foundational philosophy that design emerges from partnership rather than individual genius.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Olmsted Network. (2023). Frederick Law Olmsted.'},
    {id:2,year:1862,location:'United States',title:'Land-Grant Education Framework',description:'Morrill Act establishes land grant colleges, creating framework for agricultural and technical education that includes landscape studies.',types:['ID'],priorities:['PP01'],focusAreas:['FA01','FA06'],citation:'National Park Service. The Olmsted firm - college campuses.'},
    {id:3,year:1863,location:'Michigan, USA',title:'Integration of Landscape Gardening into Agricultural Curriculum',description:'Michigan State offers landscape gardening courses and integrates landscape gardening into agricultural curriculum.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Steiner, F., & Brooks, K. Charles Parker Halligan impact.'},
    {id:4,year:1868,location:'Illinois, USA',title:'Garden Architecture Pedagogy',description:'University of Illinois begins teaching landscape gardening/garden architecture as part of agricultural curriculum.',types:['PD'],priorities:['PP01','PP03'],focusAreas:['FA01'],citation:'Steiner, F., & Brooks, K.',connections:[3]},
    {id:5,year:1870,location:'Hampton, VA, USA',title:'Black Land-Grant Institution',description:'Hampton Normal and Agricultural Institute chartered as land-grant school, creating first institution serving both Black and Indigenous students with landscape-focused agricultural curriculum.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022). Places Journal.',tags:['black-institutions']},
    {id:6,year:1871,location:'Kansas/Iowa, USA',title:'Agricultural Integration Model',description:'Kansas State and Iowa State begin landscape gardening courses, establishing model of landscape education within agricultural colleges.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cornell AAP.',connections:[2,3]},
    {id:7,year:1874,location:'Versailles, France',title:'Formal Garden Design Pedagogy',description:'Landscape design first taught at Versailles, establishing European pedagogical tradition emphasizing geometric design principles.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'ResearchGate. (2023).'},
    {id:8,year:1878,location:'Hampton, VA, USA',title:'Indigenous Student Integration',description:'Hampton Institute matriculates first class of Indigenous students (fifteen members of Kiowa and Cheyenne tribes), establishing forced assimilationist educational model.',types:['PD'],priorities:['PP03'],focusAreas:['FA01'],citation:'Dümpelmann, S. (2022).',connections:[5],tags:['indigenous','black-institutions']},
    {id:9,year:1884,location:'Michigan, USA',title:'Horticulture-Landscape Gardening Department',description:'Liberty Hyde Bailey establishes first "Horticulture and Landscape Gardening Department" at Michigan State.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Steiner, F., & Brooks, K.',connections:[3]},
    {id:10,year:1887,location:'United States',title:'Federal Agricultural Research Framework',description:'Hatch Act allocates federal funds for land-grant colleges but systematically excludes Black institutions from funding.',types:['ID'],priorities:['PP03'],focusAreas:['FA01'],citation:'Dümpelmann, S. (2022).',connections:[2,5],tags:['black-institutions']},
    {id:11,year:1888,location:'Ithaca, NY, USA',title:'Practical-Experimental Philosophy',description:'Liberty Hyde Bailey arrives at Cornell developing "Practical and Experimental Horticulture" curriculum emphasizing hands-on learning.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Cornell CALS.',connections:[9]},
    {id:12,year:1890,location:'United States',title:'Separate-But-Equal Education',description:'Second Morrill Act requires states to establish separate land-grant institutions for people of color, institutionalizing "separate-but-equal" policy.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[2,5,10],tags:['black-institutions']},
    {id:13,year:1890,location:'United States',title:'Apprenticeship Learning Model',description:'Olmsted firm develops apprenticeship training methodology, establishing tradition of learning through direct mentorship.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Library of Congress.',connections:[1]},
    {id:14,year:1893,location:'Cambridge, MA, USA',title:'Professional Course Philosophy',description:'Harvard University offers nation first professional course in landscape architecture.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Harvard GSD.',connections:[13]},
    {id:15,year:1894,location:'Massachusetts, USA',title:'Olmsted-Washington Educational Alliance',description:'Frederick Law Olmsted Sr. meets Booker T. Washington, offering consultation on Tuskegee campus design.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[1,5],tags:['black-institutions']},
    {id:16,year:1896,location:'Ithaca, NY, USA',title:'Informal Peer Learning',description:'Cornell "Horticultural Lazy Club" under Bailey creates informal learning community emphasizing peer learning.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cornell CALS.',connections:[11]},
    {id:17,year:1898,location:'Ithaca, NY, USA',title:'Inclusive Education Philosophy',description:'David Williston becomes first professionally-trained Black landscape architect, studying under Liberty Hyde Bailey.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cornell Chronicle. (2018).',connections:[9,11,15],tags:['black-institutions','lineage']},
    {id:18,year:1900,location:'Cambridge, MA, USA',title:'First Graduate Program',description:'Frederick Law Olmsted Jr. establishes world first landscape architecture program at Harvard University.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Library of Congress.',connections:[1,14]},
    {id:19,year:1900,location:'Cambridge, MA, USA',title:'Academic Structure',description:'Harvard establishes Charles Eliot Professorship, creating first endowed chair in landscape architecture.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'PCAD.',connections:[18]},
    {id:20,year:1900,location:'Massachusetts, USA',title:'Technology Integration',description:'MIT begins offering landscape architecture courses, introducing engineering approaches to design education.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Steiner, F., & Brooks, K.'},
    {id:21,year:1900,location:'Cambridge, MA, USA',title:'Comprehensive Curriculum Structure',description:'Olmsted Jr. develops comprehensive curriculum including design studios, plant materials, construction, history, and planning.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'PCAD.',connections:[18]},
    {id:22,year:1901,location:'Groton, MA, USA',title:'Womens Professional Education',description:'Judith Motley Low establishes Lowthorpe School of Landscape Architecture for Women, first professional training exclusively for women.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Lowthorpe School. Wikipedia.',tags:['womens-education']},
    {id:23,year:1902,location:'Tuskegee, AL, USA',title:'Black Landscape Architecture Leadership',description:'David Augustus Williston hired as chief landscape gardener at Tuskegee Normal and Industrial Institute.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Dümpelmann, S. (2022).',connections:[17,15],tags:['black-institutions','lineage']},
    {id:24,year:1903,location:'Massachusetts, USA',title:'Program Expansion',description:'University of Massachusetts establishes landscape architecture program.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Steiner, F., & Brooks, K.'},
    {id:25,year:1904,location:'Ithaca, NY, USA',title:'Outdoor Art Curriculum',description:'Cornell formally establishes undergraduate landscape architecture department under Liberty Hyde Bailey.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Cornell CALS.',connections:[11,9]},
    {id:26,year:1906,location:'Ithaca, NY, USA',title:'Rural Art Pedagogy',description:'Bryant Fleming becomes Cornell first department chair. Cornell renames program "Rural Art."',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cornell CALS.',connections:[25]},
    {id:27,year:1906,location:'Tuskegee, AL, USA',title:'Community Extension Pedagogy',description:'Tuskegee launches "Movable School" extension service with George Washington Carver.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[23],tags:['black-institutions']},
    {id:28,year:1907,location:'Illinois, USA',title:'Midwest Program',description:'University of Illinois establishes formal landscape architecture program.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Steiner, F., & Brooks, K.',connections:[4]},
    {id:29,year:1907,location:'Ithaca, NY, USA',title:'Studio-Based Learning',description:'Cornell landscape architecture program moves to dedicated studio spaces in White Hall.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Cornell CALS.',connections:[25]},
    {id:30,year:1908,location:'Michigan, USA',title:'Curriculum Development',description:'University of Michigan offers first course in landscape design.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Steiner, F., & Brooks, K.'},
    {id:31,year:1909,location:'Ithaca, NY, USA',title:'Field-Based Learning',description:'Bryant Fleming establishes "Trips of Inspection" methodology at Cornell, pioneering field-based learning.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Cornell CALS.',connections:[26]},
    {id:32,year:1909,location:'Groton, MA, USA',title:'Womens Institutional Governance',description:'Lowthorpe School incorporates with all-women board of directors.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Freedoms Way.',connections:[22],tags:['womens-education']},
    {id:33,year:1910,location:'Tuskegee, AL, USA',title:'Departmental Innovation',description:'David Williston becomes director of new Department of Landscape Gardening at Tuskegee.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Dümpelmann, S. (2022).',connections:[23,17],tags:['black-institutions']},
    {id:34,year:1911,location:'Cambridge, MA, USA',title:'Information Literacy Curriculum',description:'Theodora Kimball Hubbard becomes first landscape architecture librarian at Harvard.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Hubbard, T. K. Wikipedia.',connections:[18]},
    {id:35,year:1912,location:'Ithaca, NY, USA',title:'Landscape Art Curriculum',description:'Cornell establishes Master of Landscape Design degree.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Cornell CALS.',connections:[25,26]},
    {id:36,year:1912,location:'Ithaca, NY, USA',title:'Dedicated Studio Philosophy',description:'Cornell acquires "Chicken Coop" studio facility overlooking Beebe Lake.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Cornell CALS.',connections:[29]},
    {id:37,year:1913,location:'Tuskegee, AL, USA',title:'Systematic Landscape Curriculum',description:'David Williston conducts two landscape-gardening courses at Tuskegee.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[33,23],tags:['black-institutions']},
    {id:38,year:1914,location:'Ithaca, NY, USA',title:'Comprehensive Curriculum Model',description:'Bailey proposes model curriculum including Elements of Landscape Gardening, General Design, Civic Art.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Cornell CALS.',connections:[25]},
    {id:39,year:1914,location:'Philadelphia, PA, USA',title:'Lecture-Based Introduction',description:'University of Pennsylvania introduces landscape architecture through lecture series.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'UPenn Weitzman.'},
    {id:40,year:1914,location:'United States',title:'Agricultural Extension Exclusion',description:'Smith-Lever Act funds cooperative extension but excludes Black institutions.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[27,12],tags:['black-institutions']},
    {id:41,year:1915,location:'Cambridge, MA, USA',title:'Womens Graduate Training',description:'Cambridge School of Architecture and Landscape Architecture for Women founded.',types:['ID'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cambridge School. Wikipedia.',connections:[22],tags:['womens-education']},
    {id:42,year:1915,location:'Groton, MA, USA',title:'Professional Diploma Curriculum',description:'Lowthorpe expands to three-year curriculum with diploma program.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Lowthorpe School. Wikipedia.',connections:[22,32],tags:['womens-education']},
    {id:43,year:1916,location:'Cambridge, MA, USA',title:'Collaborative Learning Philosophy',description:'Cambridge School establishes integrated curriculum where architecture and landscape architecture students collaborate.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'ACSA. (2024).',connections:[41],tags:['womens-education']},
    {id:44,year:1917,location:'Cambridge, MA, USA',title:'Beaux Arts Textbook Pedagogy',description:'Hubbard and Kimball publish "An Introduction to the Study of Landscape Design," first comprehensive educational textbook.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Hohmann, H. (2006).',connections:[18,34]},
    {id:45,year:1917,location:'Hampton, VA, USA',title:'Olmsted Brothers Consultation',description:'Olmsted Brothers consult on Hampton Institute campus alterations.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Dümpelmann, S. (2022).',connections:[5,1],tags:['black-institutions']},
    {id:46,year:1919,location:'Ås, Norway',title:'European Pioneer',description:'Norwegian University of Life Sciences establishes first academic landscape architecture program in Europe.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'ECLAS Conference. (2019).'},
    {id:47,year:1919,location:'United States',title:'Academic Classification System',description:'Theodora Kimball Hubbard develops first Library of Congress Classification system for landscape architecture.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Hubbard, T. K. Wikipedia.',connections:[34,44]},
    {id:48,year:1920,location:'Cambridge, MA, USA',title:'Historical Research Methodology',description:'Kimball Hubbard commissioned to edit Frederick Law Olmsted Sr. papers.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'TCLF.',connections:[34,47]},
    {id:49,year:1920,location:'Ithaca, NY, USA',title:'Architecture Integration',description:'Cornell moves landscape architecture to College of Architecture, promoting interdisciplinary collaboration.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cornell CALS.',connections:[35]},
    {id:50,year:1920,location:'Cambridge, MA, USA',title:'Design Process Methodology',description:'Harvard develops Beaux Arts approach and systematic design process pedagogy.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Hubbard, H. V. Wikipedia.',connections:[44,18]},
    {id:51,year:1922,location:'Ithaca, NY, USA',title:'Interdisciplinary Studio Philosophy',description:'Cornell promotes joint studios between landscape architecture, architecture, and planning.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cornell CALS.',connections:[49]},
    {id:52,year:1924,location:'Philadelphia, PA, USA',title:'Professional Practice Curriculum',description:'University of Pennsylvania establishes new department of landscape architecture with BLA degree.',types:['PD'],priorities:['PP01'],focusAreas:['FA01','FA02'],citation:'UPenn Weitzman.',connections:[39]},
    {id:53,year:1924,location:'Cambridge, MA, USA',title:'Independent Educational Institution',description:'Cambridge School incorporates as independent educational institution.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Smith College Finding Aids.',connections:[41,43],tags:['womens-education']},
    {id:54,year:1929,location:'Berlin, Germany',title:'European Expansion',description:'Berlin establishes landscape architecture program.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'ResearchGate. (2023).',connections:[46]},
    {id:55,year:1934,location:'Cambridge, MA, USA',title:'Graduate Degree Partnership',description:'Cambridge School affiliates with Smith College to grant master degrees.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Cambridge School. Wikipedia.',connections:[53,41],tags:['womens-education']},
    {id:56,year:1936,location:'Cambridge, MA, USA',title:'Bachelor Degree Innovation',description:'Cambridge School introduces bachelor degrees in architecture and landscape architecture.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Cambridge School. Wikipedia.',connections:[55],tags:['womens-education']},
    {id:57,year:1938,location:'Ithaca, NY, USA',title:'Collaborative Studio Methodology',description:'Gilmore D. Clarke appointed Dean, promoting interdisciplinary studio collaborations.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Cornell CALS.',connections:[51]},
    {id:58,year:1938,location:'Cambridge, MA, USA',title:'Modernist Design Integration',description:'Cambridge School champions modernist design combining women education with architectural innovation.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Cambridge School. Wikipedia.',connections:[55,56],tags:['womens-education']},
    {id:59,year:1939,location:'United States',title:'Accreditation Standards',description:'Cornell becomes one of first 10 landscape architecture schools accredited by ASLA.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cornell CALS.'},
    {id:60,year:1939,location:'New York, NY, USA',title:'Public Exhibition Pedagogy',description:'Cambridge School celebrates 25th anniversary with lecture series at Museum of Modern Art.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cambridge School. Wikipedia.',connections:[58],tags:['womens-education']},
    {id:61,year:1940,location:'Ithaca, NY, USA',title:'Liberal Arts Integration',description:'Cornell adds painting, sculpture, history, government, economics, sociology, geology to curriculum.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cornell University Library.',connections:[57]},
    {id:62,year:1941,location:'Lisbon, Portugal',title:'European Development',description:'Lisbon establishes landscape architecture program.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'ResearchGate. (2023).',connections:[46,54]},
    {id:63,year:1942,location:'Cambridge, MA, USA',title:'Institutional Closure',description:'Cambridge School closes as Harvard opens to women.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cambridge School. Wikipedia.',connections:[58,22],tags:['womens-education']},
    {id:64,year:1945,location:'Providence, RI, USA',title:'Institutional Absorption',description:'Lowthorpe School merges with Rhode Island School of Design.',types:['ID'],priorities:['PP03'],focusAreas:['FA05'],citation:'Lowthorpe School. Wikipedia.',connections:[22,42],tags:['womens-education']},
    {id:65,year:1947,location:'Ithaca, NY, USA',title:'External Professionals in Studio',description:'Cornell establishes visiting critic program with visits from Gropius, Philip Johnson, Frank Lloyd Wright.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Cornell AAP.',connections:[57]},
    {id:66,year:1947,location:'Wageningen, Netherlands',title:'European Network',description:'Wageningen establishes landscape architecture program.',types:['ID'],priorities:['PP02'],focusAreas:['FA03'],citation:'ResearchGate. (2023).',connections:[46,54]},
    {id:67,year:1949,location:'United States',title:'Critique-Based Pedagogy',description:'Studio education develops systematic critique methodology.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'General educational development.',connections:[50]},
    {id:68,year:1952,location:'Ithaca, NY, USA',title:'Planning Integration',description:'Cornell establishes city and regional planning department.',types:['ID'],priorities:['PP01','PP03'],focusAreas:['FA01','FA06'],citation:'Cornell AAP.',connections:[49,51]},
    {id:69,year:1954,location:'Philadelphia, PA, USA',title:'Revolutionary Pedagogy',description:'Ian McHarg becomes assistant professor at UPenn, introducing ecological science as design foundation.',types:['PD'],priorities:['PP01','PP03'],focusAreas:['FA01','FA06'],citation:'TCLF.',connections:[52]},
    {id:70,year:1956,location:'Philadelphia, PA, USA',title:'Process-Based Curriculum',description:'McHarg develops curriculum emphasizing design process rather than stylistic outcomes.',types:['PD'],priorities:['PP02'],focusAreas:['FA03','FA04'],citation:'Metropolis Magazine. (2021).',connections:[69]},
    {id:71,year:1959,location:'Philadelphia, PA, USA',title:'Man and Environment Course',description:'McHarg initiates interdisciplinary course bringing theologians and scientists to discuss human-environment relationships.',types:['PD'],priorities:['PP03'],focusAreas:['FA05','FA06'],citation:'The McHarg Center.',connections:[69]},
    {id:72,year:1960,location:'Philadelphia, PA, USA',title:'Layer-Cake Methodology',description:'McHarg develops transparent overlay analysis technique.',types:['PD'],priorities:['PP02'],focusAreas:['FA03','FA04'],citation:'Metropolis Magazine. (2021).',connections:[70]},
    {id:73,year:1960,location:'Philadelphia, PA, USA',title:'Ecological Planning Curriculum',description:'McHarg integrates natural sciences into design curriculum.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'UPenn Weitzman.',connections:[69,70]},
    {id:74,year:1960,location:'United States',title:'Anti-Beaux Arts Movement',description:'Landscape designers begin viewing Hubbard-Kimball approach as limiting.',types:['PD'],priorities:['PP03'],focusAreas:['FA05','FA06'],citation:'Living Colour Landscapes. (2014).',connections:[44,50]},
    {id:75,year:1962,location:'Ithaca, NY, USA',title:'Scientific Foundation Curriculum',description:'Cornell moves landscape architecture to College of Agriculture and Life Sciences.',types:['PD'],priorities:['PP01','PP02'],focusAreas:['FA02','FA03'],citation:'Cornell CALS.',connections:[61]},
    {id:76,year:1962,location:'Philadelphia, PA, USA',title:'Practice-Education Integration',description:'McHarg and David Wallace found Wallace-McHarg Associates.',types:['ID'],priorities:['PP01','PP03'],focusAreas:['FA01','FA06'],citation:'UPenn Weitzman.',connections:[69]},
    {id:77,year:1965,location:'Ithaca, NY, USA',title:'Program Restructuring',description:'Cornell temporarily discontinues landscape architecture program.',types:['ID'],priorities:['PP01','PP02'],focusAreas:['FA02','FA03'],citation:'Cornell University Library.',connections:[75]},
    {id:78,year:1968,location:'Global',title:'Critical Pedagogy Foundation',description:'Paulo Freire pedagogical philosophy emerges, establishing critical pedagogy for educational liberation.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'Freire, P. (1968). Pedagogy of the oppressed.',tags:['theoretical-foundation']},
    {id:79,year:1969,location:'Philadelphia, PA, USA',title:'Design with Nature Pedagogy',description:'McHarg publishes "Design with Nature," revolutionizing landscape architecture pedagogy globally.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'McHarg, I. (1969). Design with Nature.',connections:[69,70,72,73],tags:['theoretical-foundation']},
    {id:80,year:1969,location:'United States',title:'Environmental Curriculum Revolution',description:'Programs increasingly integrate environmental science and ecological principles.',types:['PD'],priorities:['PP01','PP02'],focusAreas:['FA02','FA03'],citation:'General educational development.',connections:[79]},
    {id:81,year:1970,location:'Philadelphia, PA, USA',title:'Activist Education Philosophy',description:'McHarg and Penn students organize Earth Day events.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Metropolis Magazine. (2021).',connections:[79,71]},
    {id:82,year:1970,location:'Philadelphia, PA, USA',title:'Social Science Integration',description:'Penn adds anthropologists to faculty and integrates social sciences.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'UPenn Weitzman.',connections:[71]},
    {id:83,year:1973,location:'Global',title:'Resilience Thinking Foundation',description:'C.S. Holling work on ecological resilience establishes theoretical foundation.',types:['BIB'],priorities:['PP02'],focusAreas:['FA04','FA05'],citation:'Holling, C. S. (1973). Annual Review of Ecology and Systematics.',tags:['theoretical-foundation']},
    {id:84,year:1973,location:'Ithaca, NY, USA',title:'Data-Driven Pedagogy',description:'Cornell landscape architecture re-emerges emphasizing systematic data use.',types:['PD'],priorities:['PP01','PP03'],focusAreas:['FA02','FA03'],citation:'Cornell University Library.',connections:[77]},
    {id:85,year:1974,location:'Versailles, France',title:'Institutional Development',description:'École Nationale Supérieur de Paysage Versailles established.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Land8. (2014).',connections:[7,46]},
    {id:86,year:1975,location:'United States',title:'Process-Centered Curriculum',description:'Landscape architecture education adopts process as central organizing principle.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'UPenn Weitzman.',connections:[79,82]},
    {id:87,year:1978,location:'United States',title:'GIS Integration',description:'Universities begin introducing GIS methodology building on McHarg overlay methods.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Garden Visit.',connections:[72]},
    {id:88,year:1980,location:'London, UK',title:'Feminist Collaborative Pedagogy',description:'Matrix Feminist Design Co-operative established, creating non-hierarchical learning model.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Matrix Feminist Design Co-operative. Wikipedia.',tags:['womens-education']},
    {id:89,year:1980,location:'Ithaca, NY, USA',title:'Interdisciplinary Model',description:'Cornell landscape architecture jointly administered with Agriculture and Life Sciences.',types:['PD'],priorities:['PP01'],focusAreas:['FA01'],citation:'Cornell University Library.',connections:[84]},
    {id:90,year:1982,location:'United States',title:'Computer-Aided Design',description:'CAD technology begins integration into studio teaching methodology.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Palmer, J. F. (1994).',connections:[87]},
    {id:91,year:1984,location:'London, UK',title:'Feminist Spatial Theory Integration',description:'Matrix publishes "Making Space: Women and the Man-made Environment."',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Matrix. Wikipedia.',connections:[88],tags:['womens-education']},
    {id:92,year:1985,location:'Europe',title:'Program Expansion',description:'Multiple European universities establish landscape architecture programs.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'General European development.',connections:[85,66]},
    {id:93,year:1985,location:'Global',title:'Environmental Design Philosophy',description:'Landscape architecture education worldwide adopts environmental design principles.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'General international development.',connections:[79,80]},
    {id:94,year:1988,location:'Global',title:'Feminist Epistemology Foundation',description:'Donna Haraway situated knowledges establishes feminist epistemological framework.',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Haraway, D. (1988). Feminist Studies.',tags:['theoretical-foundation','womens-education']},
    {id:95,year:1989,location:'West Berlin, Germany',title:'European Collaborative Pedagogy',description:'First Europe-wide meeting of landscape architecture schools.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Jørgensen, K. (2020).',connections:[92]},
    {id:96,year:1989,location:'Global',title:'Critical Cartography Foundation',description:'J.B. Harley work on deconstructing maps establishes critical cartographic framework.',types:['BIB'],priorities:['PP02'],focusAreas:['FA04'],citation:'Harley, J. B. (1989). Cartographica.',tags:['theoretical-foundation']},
    {id:97,year:1990,location:'Europe',title:'ECLAS Educational Organization',description:'European Council of Landscape Architecture Schools (ECLAS) established.',types:['ID'],priorities:['PP02'],focusAreas:['FA02'],citation:'ELASA. (1995).',connections:[95]},
    {id:98,year:1990,location:'Global',title:'Commons Governance Framework',description:'Elinor Ostrom work on governing the commons establishes theoretical framework.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'Ostrom, E. (1990). Cambridge University Press.',tags:['theoretical-foundation']},
    {id:99,year:1993,location:'Global',title:'Multiple Intelligences Theory',description:'Howard Gardner theory recognizing diverse forms of intelligence.',types:['BIB'],priorities:['PP02'],focusAreas:['FA02'],citation:'Gardner, H. (1993). Basic Books.',tags:['theoretical-foundation']},
    {id:100,year:1993,location:'Philadelphia, PA, USA',title:'Social Science Perspectives',description:'Penn conducts major curriculum revision adding humanist and artistic perspectives.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'UPenn Weitzman.',connections:[82]},
    {id:101,year:1994,location:'United States',title:'Technology Integration GIS CAD',description:'Survey shows 85% of BLA programs require GIS instruction.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Palmer, J. F. (1994).',connections:[87,90]},
    {id:102,year:1994,location:'Global',title:'Transgressive Pedagogy Framework',description:'bell hooks teaching to transgress emphasizes education as practice of freedom.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'hooks, b. (1994). Routledge.',connections:[78],tags:['theoretical-foundation']},
    {id:103,year:1995,location:'Philadelphia, PA, USA',title:'Design-Theory Integration',description:'Penn faculty develop collaboration between design and theoretical inquiry.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'UPenn Weitzman.',connections:[100]},
    {id:104,year:1997,location:'Cambridge, MA, USA',title:'Landscape Urbanism Emergence',description:'Charles Waldheim begins theorizing landscape urbanism at Harvard GSD.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Waldheim, C. (Ed.). (2006).',connections:[18]},
    {id:105,year:1998,location:'Global',title:'Cosmopolitan Planning Philosophy',description:'Leonie Sandercock toward cosmopolis establishes multicultural planning pedagogy framework.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Sandercock, L. (1998). John Wiley.',tags:['theoretical-foundation']},
    {id:106,year:1999,location:'Global',title:'Feminist Temporal Theory',description:'Elizabeth Grosz work on becomings establishes feminist theoretical framework for time and futures.',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Grosz, E. (1999). Cornell University Press.',tags:['theoretical-foundation']},
    {id:107,year:1999,location:'Europe',title:'Educational Alignment Bologna',description:'Bologna Declaration initiates European higher education harmonization.',types:['ID'],priorities:['PP01'],focusAreas:['FA02'],citation:'Jørgensen, K. (2020).',connections:[97]},
    {id:108,year:2000,location:'Global',title:'Environmental Phenomenology Foundation',description:'Tim Ingold work on perception of environment establishes theoretical framework.',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Ingold, T. (2000). Routledge.',tags:['theoretical-foundation']},
    {id:109,year:2000,location:'Europe',title:'Curriculum Alignment Competence-Based',description:'TUNING Educational Structures project harmonizes landscape architecture curricula.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'ECLAS.',connections:[107]},
    {id:110,year:2000,location:'Global',title:'Hybrid Digital Analog Approaches',description:'Studio teaching systematically combines analog and digital methods.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'The Landscape Library. (2025).',connections:[101]},
    {id:111,year:2002,location:'Philadelphia, PA, USA',title:'Contemporary Practice Integration',description:'James Corner appointment brings renewed emphases on ecology, technology, digital media.',types:['PD'],priorities:['PP02'],focusAreas:['FA03','FA04'],citation:'UPenn Weitzman.',connections:[103,79]},
    {id:112,year:2005,location:'Global',title:'Critical Spatial Social Justice Pedagogies',description:'Doreen Massey work on spatial theory establishes space as relational and politically constructed.',types:['BIB'],priorities:['PP02','PP03'],focusAreas:['FA04','FA05'],citation:'Massey, D. (2005). SAGE.',tags:['theoretical-foundation']},
    {id:113,year:2006,location:'Europe',title:'Academic Publishing JoLA',description:'Journal of Landscape Architecture (JoLA) founded by ECLAS.',types:['PD'],priorities:['PP02'],focusAreas:['FA03','FA04'],citation:'Jørgensen, K. (2020).',connections:[97]},
    {id:114,year:2006,location:'Global',title:'Landscape Urbanism Reader',description:'Charles Waldheim publishes "The Landscape Urbanism Reader."',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Waldheim, C. (Ed.). (2006). Princeton Architectural Press.',connections:[104],tags:['theoretical-foundation']},
    {id:115,year:2007,location:'Global',title:'New Materialist Foundations',description:'Karen Barad agential realism establishes matter as agential and relational.',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Barad, K. (2007). Duke University Press.',tags:['theoretical-foundation']},
    {id:116,year:2008,location:'United States',title:'Geodesign Pedagogy',description:'Workshop on Spatial Concepts in GIS and Design initiates geodesign methodology.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Geodesign. Wikipedia.',connections:[87,101]},
    {id:117,year:2009,location:'Global',title:'Landscape Urbanism Pedagogical Dominance',description:'Landscape urbanism becomes dominant paradigm in many programs globally.',types:['PD'],priorities:['PP02','PP03'],focusAreas:['FA03','FA04'],citation:'Contemporary development.',connections:[104,114]},
    {id:118,year:2010,location:'Europe',title:'Studio-Based Educational Standards',description:'ECLAS publishes guidance recommending minimum 50% studio-based teaching.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Jørgensen, K. (2020).',connections:[97,113]},
    {id:119,year:2010,location:'Global',title:'Vibrant Matter Theory',description:'Jane Bennett work on vibrant matter establishes matter as lively and agential.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Bennett, J. (2010). Duke University Press.',connections:[115],tags:['theoretical-foundation']},
    {id:120,year:2010,location:'Global',title:'BIM Integration',description:'Building Information Modeling begins systematic integration into studio methodology.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Río Hondo College. (2025).',connections:[110]},
    {id:121,year:2010,location:'Global',title:'Real-time Visualization',description:'Enscape, Lumion introduce real-time rendering capabilities to studio pedagogy.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'The Landscape Library. (2025).',connections:[120]},
    {id:122,year:2010,location:'Europe',title:'EMiLA Collaborative Education',description:'European Masters in Landscape Architecture establishes five-university collaborative model.',types:['ID'],priorities:['PP03'],focusAreas:['FA06'],citation:'University of Edinburgh. (2024).',connections:[107,118]},
    {id:123,year:2011,location:'Global',title:'Slow Violence Theory',description:'Rob Nixon concept of slow violence establishes framework for gradual environmental harm.',types:['BIB'],priorities:['PP02','PP03'],focusAreas:['FA06'],citation:'Nixon, R. (2011). Harvard University Press.',tags:['theoretical-foundation']},
    {id:124,year:2012,location:'Global',title:'Collaborative Studios',description:'Cloud-based platforms enable international studio collaborations.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Novatr. (2025).',connections:[122]},
    {id:125,year:2013,location:'Global',title:'Indigenous Knowledge Systems',description:'Robin Wall Kimmerer braiding sweetgrass establishes indigenous knowledge integration framework.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Kimmerer, R. W. (2013). Milkweed Editions.',tags:['theoretical-foundation','indigenous']},
    {id:126,year:2014,location:'Global',title:'Climate Activism Foundation',description:'Naomi Klein work establishes theoretical framework for climate activism.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'Klein, N. (2014). Simon & Schuster.',tags:['theoretical-foundation']},
    {id:127,year:2015,location:'Global',title:'Multispecies Thinking Foundation',description:'Anna Tsing work on multispecies thinking establishes more-than-human collaboration framework.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Tsing, A. L. (2015). Princeton University Press.',connections:[119],tags:['theoretical-foundation']},
    {id:128,year:2015,location:'Global',title:'Cheap Nature Critical Framework',description:'Jason W. Moore theorizes cheap nature as capitalism strategy for appropriating unpaid work.',types:['BIB'],priorities:['PP01','PP03'],focusAreas:['FA05','FA06'],citation:'Moore, J. W. (2015). Verso.',tags:['theoretical-foundation']},
    {id:129,year:2016,location:'Global',title:'Multispecies Collaboration Framework',description:'Donna Haraway staying with the trouble establishes multispecies collaboration framework.',types:['BIB'],priorities:['PP03'],focusAreas:['FA06'],citation:'Haraway, D. (2016). Duke University Press.',connections:[94,127],tags:['theoretical-foundation']},
    {id:130,year:2016,location:'Philadelphia, PA, USA',title:'New Landscape Declaration',description:'LAF convenes summit with over 700 landscape architects forging new vision.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Wooten, N. (2016). The Dirt.',connections:[79]},
    {id:131,year:2017,location:'Global',title:'Pluriversal Design Philosophy',description:'Arturo Escobar designs for the pluriverse establishes decolonial design framework.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Escobar, A. (2017). Duke University Press.',connections:[125],tags:['theoretical-foundation']},
    {id:132,year:2017,location:'Philadelphia, PA, USA',title:'McHarg Center Launch',description:'University of Pennsylvania launches Ian L. McHarg Center for Urbanism and Ecology.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'McHarg Center. (2017).',connections:[69,79]},
    {id:133,year:2018,location:'Global',title:'Ontological Pluralism Framework',description:'de la Cadena and Blaser establish framework for world of many worlds.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05','FA06'],citation:'De La Cadena, M., & Blaser, M. (2018). Duke University Press.',tags:['theoretical-foundation']},
    {id:134,year:2019,location:'Philadelphia, PA, USA',title:'Resurgence of Ecological Imperatives',description:'Design with Nature Now initiatives re-examine McHarg educational legacy.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Bloomberg CityLab. (2019).',connections:[79,132]},
    {id:135,year:2019,location:'Global',title:'Landscape Education Handbooks',description:'Various landscape education handbooks establish systematic approaches to pedagogy.',types:['BIB'],priorities:['PP02','PP03'],focusAreas:['FA03','FA06'],citation:'Jørgensen, K., et al. (2019). Routledge.',tags:['theoretical-foundation']},
    {id:136,year:2020,location:'Cambridge, MA, USA',title:'Climate by Design Requirement',description:'Harvard GSD mandates Climate by Design as required course for MLA candidates.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Harvard GSD. (2020).',connections:[18,104]},
    {id:137,year:2020,location:'Global',title:'Remote Learning Innovation',description:'COVID-19 pandemic accelerates hybrid and remote studio methodologies.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Contemporary development.'},
    {id:138,year:2020,location:'Washington, DC, USA',title:'Urban Landscape History Pedagogy K12',description:'Dumbarton Oaks launches Teaching Urban Landscape History and Democracy program.',types:['PD'],priorities:['PP01'],focusAreas:['FA03'],citation:'Dumbarton Oaks.'},
    {id:139,year:2020,location:'Global',title:'Design Justice Framework',description:'Sasha Costanza-Chock establishes community-led design practices framework.',types:['BIB'],priorities:['PP03'],focusAreas:['FA06'],citation:'Costanza-Chock, S. (2020).',connections:[102,98],tags:['theoretical-foundation']},
    {id:140,year:2020,location:'Global',title:'Climate-Centered Curriculum',description:'Curricula increasingly center climate change adaptation and mitigation.',types:['PD'],priorities:['PP01','PP02','PP03'],focusAreas:['FA01','FA02','FA03','FA04','FA05','FA06'],citation:'ECLAS Conference. (2025).',connections:[136]},
    {id:141,year:2020,location:'Global',title:'VR AR Integration',description:'Virtual and augmented reality technologies become accessible for design visualization.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Contemporary development.',connections:[121]},
    {id:142,year:2020,location:'Global',title:'Parametric Design Education',description:'Computational design methods and parametric modeling enter mainstream curriculum.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Novatr. (2025).',connections:[120]},
    {id:143,year:2020,location:'Global',title:'Social Justice Pedagogy',description:'Environmental justice and equity become central themes in curriculum.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Contemporary development.',connections:[139]},
    {id:144,year:2020,location:'Global',title:'Interdisciplinary Studios',description:'Systematic collaboration with data science, public health, social sciences becomes standard.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Contemporary development.',connections:[137]},
    {id:145,year:2020,location:'Global',title:'Decolonization Curriculum',description:'Education increasingly addresses decolonization and indigenous knowledge systems.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'ECLAS.',connections:[125,131]},
    {id:146,year:2020,location:'Europe',title:'Green Deal Integration',description:'European Green Deal principles integrated into pedagogical frameworks.',types:['PD'],priorities:['PP02','PP03'],focusAreas:['FA03','FA05'],citation:'ECLAS Conference. (2025).',connections:[140]},
    {id:147,year:2020,location:'Global',title:'AI-Assisted Design',description:'Artificial intelligence tools begin integration into design studio methodology.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Contemporary development.'},
    {id:148,year:2020,location:'Global',title:'Sensor-Based Learning',description:'IoT sensors and environmental monitoring integrated into field study.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Contemporary development.',connections:[116]},
    {id:149,year:2020,location:'Global',title:'Digital Twin Pedagogy',description:'Digital twin technology begins integration into landscape planning studios.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Contemporary development.',connections:[141]},
    {id:150,year:2020,location:'Global',title:'Community-Engaged Studios',description:'Participatory design methodologies become standard emphasizing community collaboration.',types:['PD'],priorities:['PP03'],focusAreas:['FA06'],citation:'Contemporary development.',connections:[139]},
    {id:151,year:2020,location:'Global',title:'Regenerative Design Pedagogy',description:'Curricula emphasize regenerative rather than merely sustainable design approaches.',types:['PD'],priorities:['PP03'],focusAreas:['FA05'],citation:'Contemporary development.',connections:[140]},
    {id:152,year:2020,location:'Global',title:'Wildness Pedagogy',description:'Curricula integrate concepts of wildness challenging wilderness/culture binaries.',types:['PD'],priorities:['PP02','PP03'],focusAreas:['FA03','FA05'],citation:'Contemporary development.'},
    {id:153,year:2020,location:'Global',title:'Decarbonisation Design Pedagogy',description:'Decarbonisation strategies integrated emphasizing carbon sequestration and net-zero design.',types:['PD'],priorities:['PP02','PP03'],focusAreas:['FA03','FA05'],citation:'Contemporary development.',connections:[140,146]},
    {id:154,year:2021,location:'Global',title:'Decolonial Environmentalism',description:'Max Liboiron pollution as colonialism connects environmental degradation to colonial structures.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'Liboiron, M. (2021). Duke University Press.',connections:[125,131],tags:['theoretical-foundation']},
    {id:155,year:2022,location:'Australia',title:'Climate Studio Pedagogy',description:'Publication of Designing Landscape Architectural Education: Studio Ecologies for Unpredictable Futures.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03','FA04'],citation:'Routledge. (2022).',connections:[136],tags:['theoretical-foundation']},
    {id:156,year:2022,location:'Global',title:'Pedagogical Innovation for Crises',description:'Emerging pedagogical frameworks for broken worlds address converging crises.',types:['BIB'],priorities:['PP03'],focusAreas:['FA05'],citation:'Cephas, J., et al. (2022). Journal of Architectural Education.',tags:['theoretical-foundation']},
    {id:157,year:2022,location:'Global',title:'Radical Pedagogical Experiments',description:'Revolutionary pedagogical experiments challenge traditional design education structures.',types:['BIB'],priorities:['PP01'],focusAreas:['FA02'],citation:'Colomina, B., et al. (2022). MIT Press.',tags:['theoretical-foundation']},
    {id:158,year:2023,location:'Global',title:'Indigenous Worldings Pedagogy',description:'Indigenous Worldings frameworks integrate indigenous cosmologies into design education.',types:['BIB'],priorities:['PP02','PP03'],focusAreas:['FA03','FA05'],citation:'Princeton University. (2023).',connections:[125,131],tags:['theoretical-foundation','indigenous']},
    {id:159,year:2023,location:'Global',title:'Landscape History Curriculum Reform',description:'Center for Cultural Landscapes revamps landscape history curriculum addressing exclusions.',types:['PD'],priorities:['PP01'],focusAreas:['FA02'],citation:'Schuler, T. A. (2023). Landscape Architecture Magazine.',connections:[138]},
    {id:160,year:2023,location:'Global',title:'Material Pedagogies',description:'Material-focused pedagogical approaches emphasize material matters in studio education.',types:['BIB'],priorities:['PP02'],focusAreas:['FA03'],citation:'Pomerantz, K. (2023). Turning points.',connections:[119],tags:['theoretical-foundation']},
    {id:161,year:2023,location:'Global',title:'Participatory Learning Methodologies',description:'Engaged urban pedagogical frameworks connect urban studies with community engagement.',types:['BIB'],priorities:['PP03'],focusAreas:['FA06'],citation:'Short, M., & Natarajan, L. (2023).',connections:[150],tags:['theoretical-foundation']},
    {id:162,year:2024,location:'Global',title:'Geologic Life Pedagogies',description:'Kathryn Yusoff geologic life connects geophysics of race to environmental design education.',types:['BIB'],priorities:['PP02','PP03'],focusAreas:['FA03','FA05'],citation:'Yusoff, K. (2024). Duke University Press.',connections:[154],tags:['theoretical-foundation']},
    {id:163,year:2025,location:'Global',title:'Machine Learning Studios',description:'Programs integrate machine learning for ecological modeling and predictive design.',types:['PD'],priorities:['PP02'],focusAreas:['FA04'],citation:'Contemporary development.',connections:[147]},
    {id:164,year:2025,location:'Global',title:'Post-Anthropocene Pedagogy',description:'Curriculum emphasizes design in context of planetary-scale environmental change.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Contemporary development.',connections:[140,155]},
    {id:165,year:2025,location:'Global',title:'Multispecies Design Education',description:'Studios incorporate more-than-human perspectives and multispecies design methodologies.',types:['PD'],priorities:['PP02'],focusAreas:['FA03'],citation:'Contemporary development.',connections:[127,129]},
    {id:166,year:2025,location:'Global',title:'Future Pedagogical Synthesis',description:'Education evolves toward synthesis of technological innovation, ecological understanding, and social justice.',types:['PD'],priorities:['PP02','PP03'],focusAreas:['FA03','FA04','FA05'],citation:'Contemporary development.',connections:[140,143,147]}
];

// Generate connections based on shared attributes and explicit lineage
function generateConnections() {
    const connections = [];
    const entries = timelineEntries;
    entries.forEach(entry => {
        if (entry.connections) {
            entry.connections.forEach(targetId => {
                connections.push({
                    source: entry.id,
                    target: targetId,
                    type: entry.tags?.includes('lineage') ? 'lineage' : 'explicit'
                });
            });
        }
    });
    for (let i = 0; i < entries.length; i++) {
        for (let j = i + 1; j < entries.length; j++) {
            const entry1 = entries[i];
            const entry2 = entries[j];
            const sharedFA = entry1.focusAreas.filter(fa => entry2.focusAreas.includes(fa));
            const sharedPP = entry1.priorities.filter(pp => entry2.priorities.includes(pp));
            const sharedTypes = entry1.types.filter(t => entry2.types.includes(t));
            if (sharedFA.length >= 2 || (sharedTypes.length > 0 && sharedPP.length > 0 && sharedFA.length > 0)) {
                const exists = connections.some(c => 
                    (c.source === entry1.id && c.target === entry2.id) ||
                    (c.source === entry2.id && c.target === entry1.id)
                );
                if (!exists) {
                    connections.push({
                        source: entry1.id,
                        target: entry2.id,
                        type: 'thematic',
                        strength: sharedFA.length + sharedPP.length * 0.5
                    });
                }
            }
        }
    }
    return connections;
}

function getTheoreticalFoundations() {
    return timelineEntries.filter(e => e.types.includes('BIB'));
}

const networkData = {
    nodes: timelineEntries,
    links: generateConnections(),
    eras: ERAS,
    focusAreas: FOCUS_AREAS,
    priorities: PEDAGOGICAL_PRIORITIES,
    entryTypes: ENTRY_TYPES,
    theoreticalFoundations: getTheoreticalFoundations()
};
